# Scrubbing and Cleaning Data - Lab

## Introduction

In the previous labs, you joined the data from our separate files into a single DataFrame.  In this lab, you'll scrub the data to get it ready for exploration and modeling!

## Objectives

You will be able to:

* Cast columns to the appropriate data types
* Identify and deal with null values appropriately
* Remove unnecessary columns
* Understand how to normalize data


## Getting Started

You'll find the resulting dataset from our work in the _Obtaining Data_ Lab stored within the file `walmart_data_not_cleaned.csv`.  

In the cells below:

* Import pandas and set the standard alias
* Import numpy and set the standard alias
* Import matplotlib.pyplot and set the standard alias
* Import seaborn and set the alias `sns` (this is the standard alias for seaborn)
* Use the ipython magic command to set all matplotlib visualizations to display inline in the notebook
* Load the dataset stored in the .csv file into a DataFrame using pandas
* Inspect the head of the DataFrame to ensure everything loaded correctly

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
walmart_df = pd.read_csv('Lego_data_merged.csv')
walmart_df.head()

,prod_id,ages,piece_count,set_name,prod_desc,prod_long_desc,theme_name,country,list_price,num_reviews,play_star_rating,review_difficulty,star_rating,val_star_rating
0,75823,6-12,277,Bird Island Egg Heist,Catapult into action and take back the eggs fr...,Use the staircase catapult to launch Red into ...,Angry Birds™,US,$29.99,2.0,4.0,Average,4.5,4.0
1,75822,6-12,168,Piggy Plane Attack,Launch a flying attack and rescue the eggs fro...,Pilot Pig has taken off from Bird Island with ...,Angry Birds™,US,$19.99,2.0,4.0,Easy,5.0,4.0
2,75821,6-12,74,Piggy Car Escape,Chase the piggy with lightning-fast Chuck and ...,Pitch speedy bird Chuck against the Piggy Car....,Angry Birds™,US,$12.99,11.0,4.3,Easy,4.3,4.1
3,21030,12+,1032,United States Capitol Building,Explore the architecture of the United States ...,Discover the architectural secrets of the icon...,Architecture,US,$99.99,23.0,3.6,Average,4.6,4.3
4,21035,12+,744,Solomon R. Guggenheim Museum®,Recreate the Solomon R. Guggenheim Museum® wit...,Discover the architectural secrets of Frank Ll...,Architecture,US,$79.99,14.0,3.2,Challenging,4.6,4.1

## Starting our Data Cleaning

To start, you'll deal with the most obvious issue: data features with the wrong data encoding.

### Checking Data Types

In the cell below, use the appropriate method to check the data type of each column.

In [3]:
walmart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 14 columns):
prod_id              10870 non-null int64
ages                 10870 non-null object
piece_count          10870 non-null int64
set_name             10870 non-null object
prod_desc            10512 non-null object
prod_long_desc       10870 non-null object
theme_name           10870 non-null object
country              10870 non-null object
list_price           10870 non-null object
num_reviews          9449 non-null float64
play_star_rating     9321 non-null float64
review_difficulty    9104 non-null object
star_rating          9449 non-null float64
val_star_rating      9301 non-null float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.2+ MB

Now, investigate some of the unique values inside of the `list_price` column.

In [6]:
walmart_df['list_price'].value_counts()[:5]

$24.3878    565
$36.5878    520
$12.1878    515
$18.2878    304
$42.6878    234
Name: list_price, dtype: int64

### Numerical Data Stored as Strings

A common issue to check for at this stage is numeric columns that have accidentally been encoded as strings. For example, you should notice that the `list_price` column above is currently formatted as a string and contains a proceeding '$'. Remove this and convert the remaining number to a `float` so that you can later model this value. After all, your primary task is to generate model to predict the price.

> Note: While the data spans a multitude of countries, assume for now that all prices have been standardized to USD.

In [25]:
walmart_df['list_price'].map(lambda x: float(x.replace('$','')))

# for value in list_p:
#     value.strip('$', '')
# return list_p

0         29.9900
1         19.9900
2         12.9900
3         99.9900
4         79.9900
5         59.9900
6         59.9900
7         49.9900
8         39.9900
9         39.9900
10        39.9900
11        34.9900
12        29.9900
13       159.9900
14        29.9900
15        19.9900
16        19.9900
17         9.9900
18         9.9900
19         9.9900
20         9.9900
21         9.9900
22         9.9900
23         9.9900
24         9.9900
25         9.9900
26         9.9900
27         9.9900
28         9.9900
29         9.9900
           ...
10840    121.9878
10841    109.7878
10842    109.7878
10843     91.4878
10844     67.0878
10845     67.0878
10846     54.8878
10847     43.9078
10848     36.5878
10849     24.3878
10850     24.3878
10851     24.3878
10852     24.3878
10853     24.3878
10854     20.7278
10855     18.2878
10856     13.4078
10857    207.3878
10858    176.8878
10859    140.2878
10860    121.9878
10861     79.2878
10862     69.5278
10863     60.9878
10864     42.6878
10865     42.6878
10866     30.4878
10867     30.4878
10868     18.2878
10869     18.2878
Name: list_price, Length: 10870, dtype: float64

### Detecting and Dealing With Null Values

Next, it's time to check for null values. How to deal with the null values will be determined by the columns containing them, and how many null values exist in each.  
 
In the cell below, get a count of how many null values exist in each column in the DataFrame.

In [31]:
walmart_df.isna().sum()

prod_id                 0
ages                    0
piece_count             0
set_name                0
prod_desc             358
prod_long_desc          0
theme_name              0
country                 0
list_price              0
num_reviews          1421
play_star_rating     1549
review_difficulty    1766
star_rating          1421
val_star_rating      1569
dtype: int64

Now, get some descriptive statistics for each of the columns. You want to see where the minimum and maximum values lie.

In [32]:
walmart_df.describe()

,prod_id,piece_count,num_reviews,play_star_rating,star_rating,val_star_rating
count,1.087000e+04,10870.000000,9449.000000,9321.000000,9449.000000,9301.000000
mean,6.181634e+04,503.936431,17.813737,4.355413,4.510319,4.214439
std,1.736390e+05,831.209318,38.166693,0.617272,0.516463,0.670906
min,6.300000e+02,1.000000,1.000000,1.000000,1.800000,1.000000
25%,2.112300e+04,97.000000,2.000000,4.000000,4.300000,4.000000
50%,4.207350e+04,223.000000,6.000000,4.500000,4.600000,4.300000
75%,7.124800e+04,556.000000,14.000000,4.800000,5.000000,4.700000
max,2.000431e+06,7541.000000,367.000000,5.000000,5.000000,5.000000

Now that you have a bit more of a understanding of each of these features you can now make an informed decision about the best strategy for dealing with the various null values. 

Some common strategies for filling null values include:
* Using the mean of the feature
* Using the median of the feature
* Inserting a random value from a normal distribution with the mean and std of the feature
* Binning

Given that most of the features with null values concern user reviews of the lego set, it is reasonable to wonder whether there is strong correlation between these features in the first place. Before proceeding, take a minute to investigate this hypothesis.

In [33]:
#answer key
import itertools

In [37]:
features = ['num_reviews', 'play_star_rating', 'star_rating', 'val_star_rating']
for combination in itertools.combinations(features, 2):   
#itertools.combinations https://docs.python.org/3/library/itertools.html
    x = combination[0]
    y = combination[1]
    temp = walmart_df[(~walmart_df[x].isnull())&(~walmart_df[y].isnull())]
    corr = round(np.corrcoef(temp[x], temp[y])[0][1], 2)
    print("Correlation between {} and {}: {}".format(x,y, corr))

Correlation between num_reviews and play_star_rating: -0.06
Correlation between num_reviews and star_rating: 0.0
Correlation between num_reviews and val_star_rating: 0.03
Correlation between play_star_rating and star_rating: 0.62
Correlation between play_star_rating and val_star_rating: 0.48
Correlation between star_rating and val_star_rating: 0.73

Note that there is substantial correlation between the `play_star_rating`, `star_rating` and `val_star_rating`. While this could lead to multicollinearity in your eventual regression model, it is too early to clearly determine this at this point. Remember that multicollinearity is a relationship between 3 or more variables while correlation simply investigates the relationship between two variables.

Additionally, these relationships provide an alternative method for imputing missing values: since they appear to be correlated, you could use these features to help impute missing values in the others features. For example, if you are missing the star_rating for a particular row but have the val_star_rating for that same entry, it seems reasonable to assume that it is a good estimate for the missing star_rating value as they are highly correlated. That said, doing so does come with risks; indeed you would be further increasing the correlation between these features which could further provoke multicollinearity in the final model.

Investigate if you could use one of the other star rating features when one is missing. How many rows have one of `play_star_rating`, `star_rating` and `val_star_rating` missing, but not all three.

In [50]:
print(len(walmart_df[(walmart_df['play_star_rating'].isnull())
                     &(walmart_df['star_rating'].isnull())
                     &(walmart_df['val_star_rating'].isnull())]))

# Number missing all three: 1421

1421

Well, it seems like when one is missing, the other two are also apt to be missing. While this has been a bit of an extended investigation, simply go ahead and fill the missing values with that features median.  

Fill in the missing `review_difficulty` values with 'unknown'.

In [60]:
walmart_df['review_difficulty'] = walmart_df['review_difficulty'].fillna('unknown')
walmart_df['review_difficulty'].isna().sum()

0

## Normalizing the Data

Now, you'll need to convert all of our numeric columns to the same scale by **_normalizing_** our dataset.  Recall that you normalize a dataset by converting each numeric value to it's corresponding z-score for the column, which is obtained by subtracting the column's mean and then dividing by the column's standard deviation for every value. 


In the cell below:

* Normalize the numeric X features by subtracting the column mean and dividing by the column standard deviation. 
(Don't bother to normalize the list_price as this is the feature you will be predicting.)

In [61]:
walmart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 14 columns):
prod_id              10870 non-null int64
ages                 10870 non-null object
piece_count          10870 non-null int64
set_name             10870 non-null object
prod_desc            10512 non-null object
prod_long_desc       10870 non-null object
theme_name           10870 non-null object
country              10870 non-null object
list_price           10870 non-null object
num_reviews          9449 non-null float64
play_star_rating     9321 non-null float64
review_difficulty    10870 non-null object
star_rating          9449 non-null float64
val_star_rating      9301 non-null float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.2+ MB

In [66]:
def normalization(column):
    return (column-column.mean())/column.std()

for val in ['piece_count', 'num_reviews', 'play_star_rating', 'star_rating', 'val_star_rating']:
    walmart_df[val] = normalization(walmart_df[val])
walmart_df.describe()

,prod_id,piece_count,num_reviews,play_star_rating,star_rating,val_star_rating
count,1.087000e+04,1.087000e+04,9.449000e+03,9.321000e+03,9.449000e+03,9.301000e+03
mean,6.181634e+04,8.497751e-18,7.143778e-18,2.286909e-18,-1.804744e-17,1.270054e-17
std,1.736390e+05,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,6.300000e+02,-6.050659e-01,-4.405343e-01,-5.435874e+00,-5.247846e+00,-4.791190e+00
25%,2.112300e+04,-4.895715e-01,-4.143334e-01,-5.757795e-01,-4.072286e-01,-3.196264e-01
50%,4.207350e+04,-3.379852e-01,-3.095300e-01,2.342363e-01,1.736454e-01,1.275300e-01
75%,7.124800e+04,6.263593e-02,-9.992317e-02,7.202458e-01,9.481441e-01,7.237386e-01
max,2.000431e+06,8.466055e+00,9.148979e+00,1.044252e+00,9.481441e-01,1.170895e+00

## Saving Your Results

While you'll once again practice one-hot encoding as you would to preprocess data before fitting a model, saving such a reperesentation of the data will eat up additional disk space. After all, a categorical variable with 10 bins will be transformed to 10 seperate features when passed through `pd.get_dummies()`. As such, while the further practice is worthwhile, save your DataFrame as is for now.

In [67]:
walmart_df.to_csv('cleaned_Lego_data_merged.csv')

## One-Hot Encoding Categorical Columns

As a final step, you'll need to deal with the categorical columns by **_one-hot encoding_** them into binary variables via the `pd.get_dummies()` method.  

When doing this, you should also subset to appropriate features. If you were to simply pass the entire DataFrame to the `pd.get_dummies()` method as it stands now, then you would end up with unique features for every single product description! (Presumably the descriptions are unique.) As such, you should first subset to the numeric features that you will eventually use in a model along with categorical variables that are not unique.

In the cell below, subset to the appropriate predictive features and then use the [`pd.get_dummies()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html) to one-hot encode the dataset.

In [69]:
features = ['ages', 'set_name', 'prod_desc', 'prod_long_desc', 'theme_name', 'country', 'review_difficulty']
pd.get_dummies(walmart_df[features])

,ages_10+,ages_10-14,ages_10-16,ages_10-21,ages_11-16,ages_12+,ages_12-16,ages_14+,ages_16+,ages_1½-3,...,country_NZ,country_PL,country_PT,country_US,review_difficulty_Average,review_difficulty_Challenging,review_difficulty_Easy,review_difficulty_Very Challenging,review_difficulty_Very Easy,review_difficulty_unknown
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
6,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
7,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
8,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
9,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
10,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
11,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
16,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
17,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
18,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
19,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
20,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
23,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
24,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
25,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
26,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
27,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
28,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
29,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10840,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10841,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10842,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10843,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10844,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10845,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10846,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10847,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10848,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10849,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
10850,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10851,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10852,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10853,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10854,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10855,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
10856,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10857,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10858,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10859,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10860,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10861,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10862,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10863,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10864,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10865,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10866,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
10867,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10868,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
10869,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0

That's it! You've now successfully scrubbed your dataset--you're now ready for data exploration and modeling!

## Summary

In this lesson, you learned gain practice with data cleaning by:

* Casting columns to the appropriate data types
* Identifying and deal with null values appropriately
* Removing unnecessary columns
* Checking for and deal with multicollinearity
* Normalizing your data